[ALPS10275267] kleaf: fix sed no temp file
only preserve the changes of abi_symbollist.raw.

as ack update, full_path/abi_symbollist.raw is too long, sed return
error: no temp file.
now we only use the name without file path and copy it under config/out_dir.

Mot-CRs-Fixed: (CR)

Change-Id: I170cf74187f0fb98f29f6510db6d89e6898a626b
Signed-off-by: wu chao <wuchao13@motorola.com>
Reviewed-on: https://gerrit.mot.com/3641933
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Varun Shrivastava <varunshrivastava@motorola.com>
Reviewed-by: Navya Vijayan <navya@motorola.com>
Submit-Approved: Jira Key