[ALPS10275267] kleaf: fix sed no temp file
[Description]
kernel/build: 1cbff62c4e816dfb5486d114942ef7edab925d44
only preserve the changes of abi_symbollist.raw.

as ack update, full_path/abi_symbollist.raw is too long, sed return
error: no temp file.
now we only use the name without file path and copy it under
config/out_dir.

[Test]
build pass, boo pass

Signed-off-by: Mingyue Han <mingyue.han@mediatek.com>
CR-Id: ALPS10275267
Feature: build process
Change-Id: I0f50a540d71eebb4b31b3e65292797e27f7156da
(cherry picked from commit 93e4a3feb62b2284d55524294bd80e540b050141)
(cherry picked from commit 350d19a6b1adab58f8421fddc799c563c35322c7)